name: casdoor_flutter_example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  casdoor_flutter_sdk: ^1.2.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

casdoor_flutter_sdk:
  app_id: wx049c70e6c2027b0b
  debug_logging: true
  ios:
    universal_link: https://testdomain.com
  # default false
  #    scene_delegate: true
  # payment is enabled by default
#    no_pay: true